=== diegogd/cakechuff/trunk/CakeChuff/database/dtd/statistics.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- DTD that represents the statistics of CakeChuff -->

	<!ELEMENT statistics (procesedPackages, faultyPackages, total_ko_cakes, total_ok_cakes, start, emergency_stops, stops)>
		<!ELEMENT procesedPackages (#PCDATA)>
		<!ELEMENT faultyPackages (#PCDATA)>
		<!ELEMENT total_ko_cakes (#PCDATA)>
		<!ELEMENT total_ok_cakes (#PCDATA)>
		<!ELEMENT start (#PCDATA)>
		<!ELEMENT emergency_stops (#PCDATA)>
		<!ELEMENT stops (#PCDATA)>

=== diegogd/cakechuff/trunk/CakeChuff/database/statistics.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE statistics SYSTEM "dtd/statistics.dtd">

<statistics>
  <procesedPackages>0</procesedPackages>
  <faultyPackages>0</faultyPackages>
  <total_ko_cakes>1232231025</total_ko_cakes>
  <total_ok_cakes>348</total_ok_cakes>
  <start>110</start>
  <emergency_stops>4</emergency_stops>
  <stops>7</stops>
</statistics>
